modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "jcraft"
logoFile= "assets/jcraft/icon.png"
logoBlur=false
version = "0.18.1"
displayName = "JCraft"
authors = "Arna, Ayutac, PlanetTeamSpeak"
description = '''
so yeah we wanted to add jojo stands to mc
'''

[[dependencies.jcraft]]
modId = "forge"
mandatory = true
versionRange = "[47.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jcraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jcraft]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.jcraft]]
modId = "azurelib"
mandatory = true
versionRange = "[1.3.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.jcraft]]
modId = "playeranimator"
mandatory = true
versionRange = "[1.0.2-rc1+1.20,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.jcraft]]
modId = "cloth_config"
mandatory = true
versionRange = "[11.1.118,)"
ordering = "AFTER"
side = "BOTH"